name: bar
description: Sample application to test cross domain request inside HUD domain.
scripts:
  setup: docker build --target=bar -t hud/{{name}}:latest -f {{config}}/Dockerfile/foobar .
  start: docker run -it --rm -d -p 60081:80 --name {{name}}  hu/{{name}}:latest
  stop: docker stop {{name}}
