# On linux machines you must chang vm.max_map_count, as specified on blacktops receipe. 
# just run:
# sudo sysctl -w vm.max_map_count=262144

name: elasticsearch62
description: Elasticsearch v6.2 service
folder: "~/.hudctl/databases/elasticsearch_v6.2"
scripts:
  setup: sudo sysctl -w vm.max_map_count=262144
  start: docker run --rm -v {{folder}}:/usr/share/elasticsearch/data -d -p9200:9200
    -p9300:9300 -e discovery.zen.minimum_master_nodes=1 --name {{name}} blacktop/elasticsearch:6.2
  stop: docker kill {{name}}
