name: sample-foo
description: Sample application to test cross domain request inside HUD domain.
scripts:
  setup: docker build --target=foo -t hud/{{name}}:latest - < {{config}}/Dockerfile/sample-foobar
  start: docker run -it --rm -d -p 60080:80 --name {{name}}  hu/{{name}}:latest
  stop: docker stop {{name}}
