name: mysql57
description: MySQL v5.7 service
folder: "~/.hudctl/databases/mysql57_data"
scripts:
  start: docker run --rm --name {{name}} -d -p7306:3306 -eMYSQL_ROOT_PASSWORD=root
    -v {{folder}}:/var/lib/mysql mysql:5.7
  stop: docker stop {{name}}
