name: rabbitmq
description: AMQP service. http://rabbitmq.hud:15672 login:guest password:guest
scripts:
  start: docker run -d --name {{name}} -p 5672:5672 rabbitmq:management
  stop: docker stop {{name}}
