name: redis
description: Redis service
folder: "~/.hudctl/databases/redis_data"
scripts:
  start: docker run --name {{name}} -d -p6379:6379 -v {{folder}}:/data redis:latest --appendonly yes
  stop: docker stop {{name}}
